# Generated by Django 4.2.23 on 2025-09-07 11:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('tenant_id', models.CharField(db_index=True, help_text='ID del tenant para multi-tenancy', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('tipo', models.CharField(choices=[('PARTICULAR', 'Cliente Particular'), ('COLEGIO', 'Colegio/Institución'), ('EMPRESA', 'Empresa')], default='PARTICULAR', max_length=20, verbose_name='Tipo de Cliente')),
                ('nombres', models.CharField(blank=True, max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(blank=True, max_length=100, verbose_name='Apellidos')),
                ('razon_social', models.CharField(blank=True, max_length=200, verbose_name='Razón Social')),
                ('nombre_comercial', models.CharField(blank=True, max_length=200, verbose_name='Nombre Comercial')),
                ('ruc', models.CharField(blank=True, max_length=11, verbose_name='RUC')),
                ('dni', models.CharField(blank=True, max_length=8, verbose_name='DNI')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('director', models.CharField(blank=True, max_length=150, verbose_name='Director')),
                ('nivel_educativo', models.CharField(blank=True, max_length=50, verbose_name='Nivel Educativo')),
                ('cantidad_alumnos', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad de Alumnos')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes_cliente',
                'ordering': ['tipo', 'razon_social', 'apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='HistorialCliente',
            fields=[
                ('tenant_id', models.CharField(db_index=True, help_text='ID del tenant para multi-tenancy', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('tipo_interaccion', models.CharField(choices=[('LLAMADA', 'Llamada Telefónica'), ('EMAIL', 'Correo Electrónico'), ('VISITA', 'Visita al Local'), ('REUNION', 'Reunión'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de Interacción')),
                ('fecha', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('usuario', models.CharField(max_length=100, verbose_name='Usuario que registra')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Historial de Cliente',
                'verbose_name_plural': 'Historial de Clientes',
                'db_table': 'clientes_historial_cliente',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ContactoCliente',
            fields=[
                ('tenant_id', models.CharField(db_index=True, help_text='ID del tenant para multi-tenancy', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('cargo', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('es_principal', models.BooleanField(default=False, verbose_name='Es contacto principal')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Contacto de Cliente',
                'verbose_name_plural': 'Contactos de Clientes',
                'db_table': 'clientes_contacto_cliente',
                'ordering': ['-es_principal', 'apellidos', 'nombres'],
            },
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['tenant_id', 'tipo'], name='clientes_cl_tenant__f6e0ee_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['tenant_id', 'dni'], name='clientes_cl_tenant__8be7b4_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['tenant_id', 'ruc'], name='clientes_cl_tenant__443eda_idx'),
        ),
    ]
