# Generated by Django 4.2.23 on 2025-09-07 11:09

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('tenant_id', models.CharField(db_index=True, help_text='ID del tenant para multi-tenancy', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('numero_orden', models.CharField(max_length=20, unique=True, verbose_name='Número de Orden')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('solicitado_por', models.CharField(max_length=100, verbose_name='Solicitado por')),
                ('responsable_produccion', models.CharField(max_length=100, verbose_name='Responsable de Producción')),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('EN_PROCESO', 'En Proceso'), ('CERRADA', 'Cerrada'), ('CANCELADA', 'Cancelada')], default='ABIERTA', max_length=20, verbose_name='Estado')),
                ('fecha_inicio_programada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Inicio Programada')),
                ('fecha_fin_programada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Fin Programada')),
                ('fecha_inicio_real', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Inicio Real')),
                ('fecha_fin_real', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Fin Real')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=10, verbose_name='Prioridad')),
                ('pedido_id', models.CharField(blank=True, max_length=36, null=True, verbose_name='ID del Pedido')),
            ],
            options={
                'verbose_name': 'Orden de Producción',
                'verbose_name_plural': 'Órdenes de Producción',
                'db_table': 'produccion_orden',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'numero_orden'], name='produccion__tenant__4b2352_idx'), models.Index(fields=['tenant_id', 'estado'], name='produccion__tenant__83017d_idx'), models.Index(fields=['tenant_id', 'fecha_creacion'], name='produccion__tenant__6eecf0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Cuadro',
            fields=[
                ('tenant_id', models.CharField(db_index=True, help_text='ID del tenant para multi-tenancy', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código del Cuadro')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre/Descripción')),
                ('alto', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Alto (cm)')),
                ('ancho', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ancho (cm)')),
                ('profundidad', models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=8, verbose_name='Profundidad (cm)')),
                ('estado', models.CharField(choices=[('EN_PRODUCCION', 'En Producción'), ('EN_ALMACEN', 'En Almacén'), ('EN_TIENDA', 'En Tienda'), ('VENDIDO', 'Vendido')], default='EN_PRODUCCION', max_length=20, verbose_name='Estado')),
                ('costo_materiales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Costo de Materiales')),
                ('costo_mano_obra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Costo de Mano de Obra')),
                ('fecha_inicio_produccion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Inicio de Producción')),
                ('fecha_fin_produccion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Fin de Producción')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cuadros/', verbose_name='Imagen')),
                ('orden_produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuadros', to='produccion.ordenproduccion', verbose_name='Orden de Producción')),
            ],
            options={
                'verbose_name': 'Cuadro',
                'verbose_name_plural': 'Cuadros',
                'db_table': 'produccion_cuadro',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'codigo'], name='produccion__tenant__e072f2_idx'), models.Index(fields=['tenant_id', 'estado'], name='produccion__tenant__65a6e3_idx'), models.Index(fields=['tenant_id', 'orden_produccion'], name='produccion__tenant__f89e12_idx')],
            },
        ),
    ]
