# Generated by Django 4.2.23 on 2025-09-07 11:09

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('tenant_id', models.CharField(db_index=True, help_text='ID del tenant para multi-tenancy', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('numero_contrato', models.CharField(max_length=20, unique=True, verbose_name='Número de Contrato')),
                ('tipo_contrato', models.CharField(choices=[('ESCOLAR', 'Contrato Escolar'), ('EMPRESARIAL', 'Contrato Empresarial'), ('EVENTO', 'Contrato de Evento')], max_length=20, verbose_name='Tipo de Contrato')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ACTIVO', 'Activo'), ('VENCIDO', 'Vencido'), ('RENOVADO', 'Renovado'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=20, verbose_name='Estado')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('fecha_firma', models.DateField(blank=True, null=True, verbose_name='Fecha de Firma')),
                ('descripcion_servicio', models.TextField(verbose_name='Descripción del Servicio')),
                ('alcance', models.TextField(blank=True, verbose_name='Alcance')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monto Total')),
                ('forma_pago', models.CharField(blank=True, max_length=100, verbose_name='Forma de Pago')),
                ('terminos_condiciones', models.TextField(blank=True, verbose_name='Términos y Condiciones')),
                ('clausulas_especiales', models.TextField(blank=True, verbose_name='Cláusulas Especiales')),
                ('renovacion_automatica', models.BooleanField(default=False, verbose_name='Renovación Automática')),
                ('periodo_renovacion_meses', models.PositiveIntegerField(blank=True, null=True, verbose_name='Período de Renovación (meses)')),
                ('responsable_empresa', models.CharField(max_length=100, verbose_name='Responsable de la Empresa')),
                ('responsable_cliente', models.CharField(blank=True, max_length=100, verbose_name='Responsable del Cliente')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'db_table': 'contratos_contrato',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='RenovacionContrato',
            fields=[
                ('tenant_id', models.CharField(db_index=True, help_text='ID del tenant para multi-tenancy', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_renovacion', models.DateField(verbose_name='Fecha de Renovación')),
                ('motivo_renovacion', models.TextField(blank=True, verbose_name='Motivo de Renovación')),
                ('cambios_realizados', models.TextField(blank=True, verbose_name='Cambios Realizados')),
                ('contrato_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renovaciones', to='contratos.contrato', verbose_name='Contrato Original')),
                ('contrato_renovado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='renovacion_de', to='contratos.contrato', verbose_name='Contrato Renovado')),
            ],
            options={
                'verbose_name': 'Renovación de Contrato',
                'verbose_name_plural': 'Renovaciones de Contratos',
                'db_table': 'contratos_renovacion',
                'ordering': ['-fecha_renovacion'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoContrato',
            fields=[
                ('tenant_id', models.CharField(db_index=True, help_text='ID del tenant para multi-tenancy', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('tipo_documento', models.CharField(choices=[('CONTRATO', 'Contrato'), ('ANEXO', 'Anexo'), ('ADDENDUM', 'Addendum'), ('RECIBO', 'Recibo'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de Documento')),
                ('nombre_documento', models.CharField(max_length=200, verbose_name='Nombre del Documento')),
                ('archivo', models.FileField(upload_to='contratos/documentos/', verbose_name='Archivo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='contratos.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Documento de Contrato',
                'verbose_name_plural': 'Documentos de Contratos',
                'db_table': 'contratos_documento',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='ContratoEscolar',
            fields=[
                ('tenant_id', models.CharField(db_index=True, help_text='ID del tenant para multi-tenancy', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('año_escolar', models.CharField(max_length=10, verbose_name='Año Escolar')),
                ('cantidad_alumnos', models.PositiveIntegerField(verbose_name='Cantidad de Alumnos')),
                ('grados_incluidos', models.CharField(max_length=200, verbose_name='Grados Incluidos')),
                ('incluye_foto_individual', models.BooleanField(default=True, verbose_name='Incluye Foto Individual')),
                ('incluye_foto_grupal', models.BooleanField(default=False, verbose_name='Incluye Foto Grupal')),
                ('incluye_recordatorios', models.BooleanField(default=True, verbose_name='Incluye Recordatorios')),
                ('cantidad_recordatorios_por_alumno', models.PositiveIntegerField(default=1, verbose_name='Recordatorios por Alumno')),
                ('fecha_sesion_fotos', models.DateField(blank=True, null=True, verbose_name='Fecha de Sesión de Fotos')),
                ('fecha_entrega_recordatorios', models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega de Recordatorios')),
                ('plantilla_recordatorio', models.CharField(blank=True, max_length=100, verbose_name='Plantilla de Recordatorio')),
                ('diseño_personalizado', models.BooleanField(default=False, verbose_name='Diseño Personalizado')),
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_escolar', to='contratos.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Contrato Escolar',
                'verbose_name_plural': 'Contratos Escolares',
                'db_table': 'contratos_escolar',
            },
        ),
        migrations.CreateModel(
            name='PagoContrato',
            fields=[
                ('tenant_id', models.CharField(db_index=True, help_text='ID del tenant para multi-tenancy', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('numero_pago', models.CharField(max_length=20, verbose_name='Número de Pago')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de Pago')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto')),
                ('metodo_pago', models.CharField(max_length=50, verbose_name='Método de Pago')),
                ('referencia', models.CharField(blank=True, max_length=100, verbose_name='Referencia')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('numero_recibo', models.CharField(blank=True, max_length=20, verbose_name='Número de Recibo')),
                ('archivo_recibo', models.FileField(blank=True, null=True, upload_to='contratos/recibos/', verbose_name='Archivo del Recibo')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='contratos.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Pago de Contrato',
                'verbose_name_plural': 'Pagos de Contratos',
                'db_table': 'contratos_pago',
                'ordering': ['-fecha_pago'],
                'unique_together': {('contrato', 'numero_pago')},
            },
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['tenant_id', 'numero_contrato'], name='contratos_c_tenant__2a27b0_idx'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['tenant_id', 'cliente'], name='contratos_c_tenant__30ea10_idx'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['tenant_id', 'estado'], name='contratos_c_tenant__e1b659_idx'),
        ),
    ]
